#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import importlib.util
import re
import sys
import types
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
LABELS_PATH = ROOT / "services/api/app/ai/labels.py"
OUTPUT_PATH = ROOT / "apps/web/src/domain/generated/taxonomy.ts"


def _load_module(module_name: str, path: Path) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"Unable to load module spec for {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def load_labels_module() -> types.ModuleType:
    return _load_module("app.ai.labels", LABELS_PATH)


def ts_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def render_ts_value(value: Any, indent: int = 0) -> str:
    pad = "  " * indent
    if isinstance(value, str):
        return ts_string(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        rendered_items = [f"{pad}  {render_ts_value(item, indent + 1)}," for item in value]
        return "[\n" + "\n".join(rendered_items) + f"\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rendered_items: list[str] = []
        for key, item in value.items():
            rendered_key = key if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", key) else ts_string(key)
            rendered_items.append(f"{pad}  {rendered_key}: {render_ts_value(item, indent + 1)},")
        return "{\n" + "\n".join(rendered_items) + f"\n{pad}}}"
    raise SystemExit(f"Unsupported taxonomy value type: {type(value)!r}")


def render_export() -> str:
    labels = load_labels_module()

    exports = [
        "export const CATEGORY_LABELS = " + render_ts_value(tuple(labels.CATEGORY_LABELS)) + " as const;",
        "export type BackendCategory = (typeof CATEGORY_LABELS)[number];",
        "",
        "export const SUBCATEGORY_LABELS = " + render_ts_value(dict(labels.SUBCATEGORY_LABELS)) + " as const;",
        (
            "export type BackendSubcategory = {\n"
            "  [Category in keyof typeof SUBCATEGORY_LABELS]: "
            "(typeof SUBCATEGORY_LABELS)[Category][number];\n"
            "}[keyof typeof SUBCATEGORY_LABELS];"
        ),
        "",
        "export const STYLE_LABELS = " + render_ts_value(tuple(labels.STYLE_LABELS)) + " as const;",
        "export type StyleLabel = (typeof STYLE_LABELS)[number];",
        "",
        "export const MATERIAL_LABELS = " + render_ts_value(tuple(labels.MATERIAL_LABELS)) + " as const;",
        "export type MaterialLabel = (typeof MATERIAL_LABELS)[number];",
        "",
        "export const ATTRIBUTE_LABELS = " + render_ts_value(tuple(labels.ATTRIBUTE_LABELS)) + " as const;",
        "export type AttributeLabel = (typeof ATTRIBUTE_LABELS)[number];",
        "",
        "export const SUBCATEGORY_TO_CATEGORY = " + render_ts_value(dict(labels.SUBCATEGORY_TO_CATEGORY)) + " as const;",
    ]

    body = "\n".join(exports).strip()
    return (
        "// Generated by scripts/contracts/export_taxonomy.py.\n"
        "// Do not edit manually. Update services/api/app/ai/labels.py and regenerate instead.\n\n"
        f"{body}\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export taxonomy labels from backend source of truth")
    parser.add_argument("--check", action="store_true", help="Fail if generated output is out of date")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = render_export()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""

    if args.check:
        if current != expected:
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile=str(OUTPUT_PATH),
                tofile="generated",
                lineterm="",
            )
            for line in diff:
                print(line)
            print(f"Taxonomy export drift detected in {OUTPUT_PATH.relative_to(ROOT)}")
            return 1
        print(f"Taxonomy export is up to date: {OUTPUT_PATH.relative_to(ROOT)}")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
