import type { ReactElement } from 'react';
import Card from '../components/Card';

const Outfits = (): ReactElement => (
  <div className="space-y-4">
    <h1 className="text-2xl font-semibold text-neutral-900">Outfits</h1>
    <Card title="Coming soon" description="Curated looks generated by StyleUs will appear here.">
      <p className="text-sm text-neutral-500">
        The outfits experience is under construction. In the meantime, keep building your wardrobe and
        we&apos;ll suggest head-to-toe looks in a future update.
      </p>
    </Card>
  </div>
);

export default Outfits;
